### ISSUE TITLE
Review Task 01 User-Directed Messages

### ISSUE THREAD

**Issue by christianj6** [ALLUOS/ALLUOS.github.io#17]
**Description**
To refine and/or improve the existing messages and instructions sent to each user, please review the .json file referenced by group 1 and submit suggested changes.

**Acceptance Criteria**
- [x] suggested changes submitted as modified json file to group 1

**Comment by maralthesage** [comment]
Here is the modified content of the .json file. I copy-pasted it into a Word file in order to change it(So that the original data remains intact in case someone wants to compare them). I have made a few changes to the existing sentences and added some new ones to have more variation. I hope it works.
[Task instruction.docx](https://github.com/ALLUOS/ALLUOS.github.io/files/4800910/Task.instruction.docx)
